[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Add OpenAI API key as a comment here. Don't hardcode the actual key in this file.
  # Set this in the Netlify dashboard for security: OPENAI_API_KEY
  # Disable sourcemaps processing
  NEXT_DISABLE_SOURCEMAPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# Custom local plugin to fix missing files
[[plugins]]
  package = "./netlify-build-plugin.js"

# Remove the redirect as it might interfere with Next.js routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = false 