[build]
  command = "node fix-bcrypt-netlify.js && node netlify-build.js"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Disable Prisma's automatic generation to fix caching issues
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  # Add OpenAI API key as a comment here. Don't hardcode the actual key in this file.
  # Set this in the Netlify dashboard for security: OPENAI_API_KEY
  # Disable sourcemaps processing
  NEXT_DISABLE_SOURCEMAPS = "true"
  # Force rebuild native modules - helps with bcrypt
  NPM_FLAGS = "--prefer-offline --no-audit"
  BUILD_NATIVE_MODULES = "true"

# Define build lifecycle hooks
[build.lifecycle]
  onBuild = "npm rebuild bcrypt --build-from-source || npm install bcrypt --build-from-source"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# Custom local plugin to fix missing files
[[plugins]]
  package = "./netlify-nextjs-fix-plugin"

# Remove the redirect as it might interfere with Next.js routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = false 