[build]
  command = "npm run netlify-build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':(exclude)netlify.toml'"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Next.js specific settings
  NEXT_SKIP_TYPESCRIPT_CHECK = "1"
  NEXT_DISABLE_SOURCEMAPS = "1"
  
  # Disable experimental features
  NODE_OPTIONS = "--no-experimental-fetch"
  
  # Database settings
  DATABASE_URL = "file:./prisma/dev.db"
  
  # Disable Prisma telemetry and postinstall
  PRISMA_TELEMETRY_DISABLED = "1"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "1"
  PRISMA_SCHEMA_DISABLE_CACHE = "1"
  
  # Shell settings
  SHELL = "/bin/bash"
  
  # Bcrypt settings
  SKIP_BCRYPT_NATIVE_BUILD = "1"

# Define specific prebuild steps
[build.lifecycle]
  onBuild = "cp prisma/schema.prisma prisma/schema.backup.prisma || true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    enable_middleware = true
    enable_function_logs = true
    use_edge_functions = true

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# Disable asset optimization to avoid conflicts with Next.js
[build.processing]
  skip_processing = true

# Add a redirect for SPA fallback
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-middleware"
  status = 200
  force = false 