[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  PYTHON_VERSION = "3.9"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Disable Prisma's automatic generation to fix caching issues
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  # Add OpenAI API key as a comment here. Don't hardcode the actual key in this file.
  # Set this in the Netlify dashboard for security: OPENAI_API_KEY
  # Disable sourcemaps processing
  NEXT_DISABLE_SOURCEMAPS = "true"

# Add a pre-build command to force Prisma generate
[build.lifecycle]
  onPreBuild = "npx prisma generate"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# Custom local plugin to fix missing files
[[plugins]]
  package = "./netlify-nextjs-fix-plugin"

# Remove the redirect as it might interfere with Next.js routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = false 